// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWqWHTjYG6uQCmwbSFJjb5Xuz-8IOMiY',
    appId: '1:897396323815:web:41c56e9644f467ed05b942',
    messagingSenderId: '897396323815',
    projectId: 'rhyme-b2804',
    authDomain: 'rhyme-b2804.firebaseapp.com',
    storageBucket: 'rhyme-b2804.firebasestorage.app',
    measurementId: 'G-BWWZR3FGWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyihg-aqa10hcTALmG1cMALDKXON1-CSI',
    appId: '1:897396323815:android:a38d1f90d00c30de05b942',
    messagingSenderId: '897396323815',
    projectId: 'rhyme-b2804',
    storageBucket: 'rhyme-b2804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0YAMaJNG0Wf0jm2KiwNbpubpNyY4Tr14',
    appId: '1:897396323815:ios:7460c2605896edd505b942',
    messagingSenderId: '897396323815',
    projectId: 'rhyme-b2804',
    storageBucket: 'rhyme-b2804.firebasestorage.app',
    iosBundleId: 'com.example.rhyme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0YAMaJNG0Wf0jm2KiwNbpubpNyY4Tr14',
    appId: '1:897396323815:ios:7460c2605896edd505b942',
    messagingSenderId: '897396323815',
    projectId: 'rhyme-b2804',
    storageBucket: 'rhyme-b2804.firebasestorage.app',
    iosBundleId: 'com.example.rhyme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpWqWHTjYG6uQCmwbSFJjb5Xuz-8IOMiY',
    appId: '1:897396323815:web:716a3a4448bcacee05b942',
    messagingSenderId: '897396323815',
    projectId: 'rhyme-b2804',
    authDomain: 'rhyme-b2804.firebaseapp.com',
    storageBucket: 'rhyme-b2804.firebasestorage.app',
    measurementId: 'G-6L8QZC0T1V',
  );
}
